# =================================================================
# 🔒 SECURITY: Default values are for LOCAL DEVELOPMENT ONLY!
# For production, always set environment variables explicitly.
# Never use the default passwords shown below in production!
# =================================================================

version: '3.8'
services:
  db:
    image: postgres:15
    container_name: urlshortener-db
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-urlshortener_dev}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-local_dev_only_password}'
      POSTGRES_DB: '${POSTGRES_DB:-urlshortener_dev_db}'
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-urlshortener_dev}']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-api
    command: npm run start
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://urlshortener_dev:local_dev_only_password@db:5432/urlshortener_dev_db}
      - PORT=${PORT:-8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - JWT_SECRET=${JWT_SECRET:-local-dev-jwt-secret-NOT-FOR-PRODUCTION}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-3600s}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - '${PORT:-8080}:${PORT:-8080}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
