version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  db_data:
